syntax = "proto3";

package lingcat.classes;

/** 
 * =======================================================
 *
 *                          基础类
 *
 * =======================================================
 */

message EncryptedMessage {
    uint32 seq = 1;
    bytes iv = 2;
    bytes data = 3;
    bytes aad = 4;
}

message IUser {
    string id = 1;
    optional string username = 2;
    string nickname = 3;
    optional string description = 4;
    optional string avatar_file_hash = 5;
}

message IChatAdmin {
    string id = 1;
    optional string username = 2;
    string nickname = 3;
    optional string description = 4;
    optional string avatar_file_hash = 5;
    
    string role = 6;
    string permissions = 7;
}

message IChat {
    string id = 1;
    optional string title = 2;
    optional string chat_unique = 3;
    string type = 4;
    optional string avatar_file_hash = 5;
    string settings = 6;
    uint32 last_message_id = 7;
    uint64 last_message_time = 8;
    optional string description = 9;
    optional string last_message_text = 10; 
}

message IFile {
    string hash = 1;
    optional string first_upload_file_name = 2;
    optional string belong_to_chat_id = 3;
    string mime = 4;
    uint64 uploaded_at = 5;
}

message IMessage {
    uint32 id = 1;
    optional string sender_user_id = 2;
    optional bool system = 3;
    string chat_id = 4;
    string text = 5;
    uint64 time = 6;
}
