syntax = "proto3";

/** 
 * =======================================================
 *
 *                       方法调用
 *
 * =======================================================
 */

package lingcat.methods;

message Error_Response {
    uint32 request_method = 1;
    optional string message = 2;
    optional uint32 code = 3;
}

message HandShake_Request {
    bytes client_public_key = 1;
}

message HandShake_Response {
    bytes salt = 1;
    bytes message_to_be_verify = 2;
    bytes server_public_key = 3;
}

message Ping_Request {
    uint64 time = 1;
}

message Ping_Response {
    uint64 usage = 1;
}

message User_Registration_Request {
    optional string username = 1;
    string password = 2;
    string nickname = 3;
}

message User_Registration_Response {
    string id = 1;
}

message User_Login_Request {
    string account = 1;
    string password = 2;
}

message User_Login_Response {
    string access_token = 1;
}
