syntax = "proto3";

/** 
 * =======================================================
 *
 *                       方法调用
 *
 * =======================================================
 */

package lingcat.methods;

import "./classes.proto";

message Error_Response {
    uint32 request_method = 1;
    optional string message = 2;
    optional uint32 code = 3;
}

message HandShake_Request {
    bytes client_public_key = 1;
}

message HandShake_Response {
    bytes salt = 1;
    bytes message_to_be_verify = 2;
    bytes server_public_key = 3;
}

message Ping_Request {
    uint64 time = 1;
}

message Ping_Response {
    uint64 usage = 1;
}

message User_Registration_Request {
    optional string username = 1;
    string password = 2;
    string nickname = 3;
}

message User_Registration_Response {
    string id = 1;
}

message User_Login_Request {
    string account = 1;
    string password = 2;
}

message User_Login_Response {
    string access_token = 1;
}

message Request_File_Upload_Request {
    string access_token = 1;
}

message Request_File_Upload_Response {
    string token = 1;
}

message Request_File_Access_Request {
    string access_token = 1;
}

message Request_File_Access_Response {
    string token = 1;
}

message Authorize_Request {
    string access_token = 1;
    string session_id = 2;
}

message Authorize_Response {}

message Query_User_Info_Request {
    string access_token = 1;
    string user_id = 2;
}

message Query_My_User_Info_Request {
    string access_token = 1;
}

/** see { @link classes-interfaces.ts } */
message Query_User_Info_Response {
    IUser info = 1;
}

message Query_My_User_Info_Response {
    IUser info = 1;
}

message Update_My_Profile_Request {
    string access_token = 1;
    optional string avatar_file_hash = 2;
    optional string username = 3;
    optional string nickname = 4;
    optional string description = 5;
}

message Update_My_Profile_Response {}

message Update_Chat_Profile_Request {
    string access_token = 1;
    string chat_id = 2;
    optional string avatar_file_hash = 3;
    optional string title = 4;
    optional string description = 5;
    optional string unique = 6;
}

message Update_Chat_Profile_Response {}

message Send_Chat_Message_Request {
    string access_token = 1;
    string chat_id = 2; 
    string text = 3; 
}

message Send_Chat_Message_Response {
    uint32 id = 1;
}

message Receive_Chat_Message_Event {
    IMessage msg = 1;
}

message Get_Chat_Messages_Request {
    string access_token = 1;
    string chat_id = 2;
    optional uint32 before = 3;
    optional uint32 after = 4;
    optional uint32 limit = 5;
}

message Get_Chat_Messages_Response {
    repeated IMessage messages = 1;
}

message Query_Chat_Info_Request {
    string access_token = 1;
    string chat_id = 2;
}

message Query_Chat_Info_Response {
    IChat info = 1;
}

message Get_Or_Create_Private_Chat_Request {
    string access_token = 1;
    string target_user_id = 2;
}

message Get_Or_Create_Private_Chat_Response {
    string chat_id = 1;
}

// 获取我的所有对话（分页）
message Get_My_Chats_Request {
    string access_token = 1;
    optional uint32 limit = 2;
    optional uint32 offset = 3;
}

message Get_My_Chats_Response {
    repeated IChat chats = 1;
}

// 获取我的收藏对话（分页）
message Get_My_Favourite_Chats_Request {
    string access_token = 1;
    optional uint32 limit = 2;
    optional uint32 offset = 3;
}

message Get_My_Favourite_Chats_Response {
    repeated IChat chats = 1;
}

// 搜索我的对话（关键词）
message Search_My_Chats_Request {
    string access_token = 1;
    string keyword = 2;
    optional uint32 limit = 3;
}

message Search_My_Chats_Response {
    repeated IChat chats = 1;
}

message Get_Another_User_From_Private_Chat_Request {
    string access_token = 1;
    string target_chat_id = 2;
}

message Get_Another_User_From_Private_Chat_Response {
    string user_id = 1;
}

message Set_Chat_Favourited_Request {
    string access_token = 1;
    string chat_id = 2;
    bool favourited = 3;
}

message Set_Chat_Favourited_Response {}

message Get_User_Id_By_Username_Request {
    string access_token = 1;
    string username = 2;
}

message Get_User_Id_By_Username_Response {
    string user_id = 1;
}

message Resolve_Chat_Identifier_Request {
    string access_token = 1;
    string identifier = 2;
}

message Resolve_Chat_Identifier_Response {
    string chat_id = 1;
}

message Update_My_Chats_Event {}

message Create_Group_Request {
    string access_token = 1;
    string title = 2;
    optional string unique = 3;
}

message Create_Group_Response {
    string chat_id = 1;
}

message Join_Chat_Request {
    string access_token = 1;
    string chat_id = 2;
    optional string answer = 3;
}

message Join_Chat_Response {
    bool pending_approval = 1;
}

message Remove_Chat_Member_Request {
    string access_token = 1;
    string chat_id = 2;
    string target_user_id = 3;
}

message Remove_Chat_Member_Response {}

message Update_Chat_Settings_Request {
    string access_token = 1;
    string chat_id = 2;
    string settings = 3;
}

message Update_Chat_Settings_Response {}

message Get_Chat_Admins_Request {
    string access_token = 1;
    string chat_id = 2;
}

message Get_Chat_Admins_Response {
    repeated IChatAdmin admins = 1;
}

message Get_Chat_Members_Request {
    string access_token = 1;
    string chat_id = 2;
}

message Get_Chat_Members_Response {
    repeated IUser members = 1;
}

message Add_Chat_Admin_Request {
    string access_token = 1;
    string chat_id = 2;
    string target_user_id = 3;
    optional string permissions = 4;
}

message Add_Chat_Admin_Response {}

message Edit_Chat_Admin_Permissions_Request {
    string access_token = 1;
    string chat_id = 2;
    string target_user_id = 3;
    string permissions = 4;
}

message Edit_Chat_Admin_Permissions_Response {}

message Remove_Chat_Admin_Request {
    string access_token = 1;
    string chat_id = 2;
    string target_user_id = 3;
}

message Remove_Chat_Admin_Response {}

message Verify_Password_Identity_Request {
    string access_token = 1;
    optional string old_password = 2;
    // optional string verification_code = 3;
}

message Verify_Password_Identity_Response {
    string change_token = 1;
}

message Change_Password_Request {
    string access_token = 1;
    string change_token = 2;
    string new_password = 3;
}

message Change_Password_Response {}
