pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
    google()
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/google' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://repo.huaweicloud.com/repository/maven' }
  }
}

dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    mavenCentral()
    google()
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/google' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://repo.huaweicloud.com/repository/maven' }
  }
}

include(":app", ":moon3")