package lingcat.protocol;

public class Methods {
    public static final int Error_Response = 0x0;
    public static final int HandShake_Request = 0x1;
    public static final int HandShake_Response = 0x2;
    public static final int Ping_Request = 0x3;
    public static final int Ping_Response = 0x4;
    public static final int User_Registration_Request = 0x5;
    public static final int User_Registration_Response = 0x6;
    public static final int User_Login_Request = 0x7;
    public static final int User_Login_Response = 0x8;
    public static final int Request_File_Upload_Request = 0x9;
    public static final int Request_File_Upload_Response = 0x10;
    public static final int Authorize_Request = 0x11;
    public static final int Authorize_Response = 0x12;
    public static final int Query_User_Info_Request = 0x13;
    public static final int Query_User_Info_Response = 0x14;
    public static final int Update_My_Profile_Request = 0x15;
    public static final int Update_My_Profile_Response = 0x16;
    public static final int Update_Chat_Profile_Request = 0x17;
    public static final int Update_Chat_Profile_Response = 0x18;
    public static final int Query_My_User_Info_Request = 0x19;
    public static final int Query_My_User_Info_Response = 0x20;
    public static final int Request_File_Access_Request = 0x21;
    public static final int Request_File_Access_Response = 0x22;
    public static final int Send_Chat_Message_Request = 0x23;
    public static final int Send_Chat_Message_Response = 0x24;
    public static final int Get_Chat_Messages_Request = 0x25;
    public static final int Get_Chat_Messages_Response = 0x26;
    public static final int Query_Chat_Info_Request = 0x27;
    public static final int Query_Chat_Info_Response = 0x28;
    public static final int Get_Or_Create_Private_Chat_Request = 0x29;
    public static final int Get_Or_Create_Private_Chat_Response = 0x30;
    public static final int Get_My_Chats_Request = 0x33;
    public static final int Get_My_Chats_Response = 0x34;
    public static final int Get_My_Favourite_Chats_Request = 0x35;
    public static final int Get_My_Favourite_Chats_Response = 0x36;
    public static final int Search_My_Chats_Request = 0x37;
    public static final int Search_My_Chats_Response = 0x38;
    public static final int Get_Another_User_From_Private_Chat_Request = 0x39;
    public static final int Get_Another_User_From_Private_Chat_Response = 0x40;
    public static final int Set_Chat_Favourited_Request = 0x41;
    public static final int Set_Chat_Favourited_Response = 0x42;
    public static final int Get_User_Id_By_Username_Request = 0x43;
    public static final int Get_User_Id_By_Username_Response = 0x44;
    public static final int Create_Group_Request = 0x45;
    public static final int Create_Group_Response = 0x46;
    public static final int Set_Chat_Admin_Request = 0x47;
    public static final int Set_Chat_Admin_Response = 0x48;
    public static final int Resolve_Chat_Identifier_Request = 0x49;
    public static final int Resolve_Chat_Identifier_Response = 0x50;
    public static final int Join_Chat_Request = 0x51;
    public static final int Join_Chat_Response = 0x52;
    public static final int Remove_Chat_Member_Request = 0x53;
    public static final int Remove_Chat_Member_Response = 0x54;
    public static final int Update_Chat_Settings_Request = 0x55;
    public static final int Update_Chat_Settings_Response = 0x56;
    public static final int Get_Chat_Admins_Request = 0x57;
    public static final int Get_Chat_Admins_Response = 0x58;
    public static final int Get_Chat_Members_Request = 0x59;
    public static final int Get_Chat_Members_Response = 0x60;
    public static final int Add_Chat_Admin_Request = 0x61;
    public static final int Add_Chat_Admin_Response = 0x62;
    public static final int Edit_Chat_Admin_Permissions_Request = 0x63;
    public static final int Edit_Chat_Admin_Permissions_Response = 0x64;
    public static final int Remove_Chat_Admin_Request = 0x65;
    public static final int Remove_Chat_Admin_Response = 0x66;
    public static final int Verify_Password_Identity_Request = 0x67;
    public static final int Verify_Password_Identity_Response = 0x68;
    public static final int Change_Password_Request = 0x69;
    public static final int Change_Password_Response = 0x70;
    public static final int Edit_Chat_Message_Request = 0x71;
    public static final int Edit_Chat_Message_Response = 0x72;
    public static final int Start_Meeting_Request = 0x74;
    public static final int Start_Meeting_Response = 0x75;
    public static final int Get_Meeting_Token_Request = 0x76;
    public static final int Get_Meeting_Token_Response = 0x77;
    public static final int End_Meeting_Request = 0x78;
    public static final int End_Meeting_Response = 0x79;
    public static final int Get_Active_Meeting_Request = 0x82;
    public static final int Get_Active_Meeting_Response = 0x83;
    public static final int Exchange_OAuth_Code_Request = 0x84;
    public static final int Exchange_OAuth_Code_Response = 0x85;
    public static final int Get_OAuth_Bindings_Request = 0x86;
    public static final int Get_OAuth_Bindings_Response = 0x87;
    public static final int Unbind_OAuth_Request = 0x88;
    public static final int Unbind_OAuth_Response = 0x89;

    public static final int Receive_Chat_Message_Event = 0x31;
    public static final int Update_My_Chats_Event = 0x32;
    public static final int Message_Edited_Event = 0x73;
    public static final int Meeting_Started_Event = 0x80;
    public static final int Meeting_Ended_Event = 0x81;

    private Methods() { }

    public static String getMethodName(int id) {
        switch (id) {
            case Error_Response: return "Error_Response";
            case HandShake_Request: return "HandShake_Request";
            case HandShake_Response: return "HandShake_Response";
            case Ping_Request: return "Ping_Request";
            case Ping_Response: return "Ping_Response";
            case User_Registration_Request: return "User_Registration_Request";
            case User_Registration_Response: return "User_Registration_Response";
            case User_Login_Request: return "User_Login_Request";
            case User_Login_Response: return "User_Login_Response";
            case Request_File_Upload_Request: return "Request_File_Upload_Request";
            case Request_File_Upload_Response: return "Request_File_Upload_Response";
            case Authorize_Request: return "Authorize_Request";
            case Authorize_Response: return "Authorize_Response";
            case Query_User_Info_Request: return "Query_User_Info_Request";
            case Query_User_Info_Response: return "Query_User_Info_Response";
            case Update_My_Profile_Request: return "Update_My_Profile_Request";
            case Update_My_Profile_Response: return "Update_My_Profile_Response";
            case Update_Chat_Profile_Request: return "Update_Chat_Profile_Request";
            case Update_Chat_Profile_Response: return "Update_Chat_Profile_Response";
            case Query_My_User_Info_Request: return "Query_My_User_Info_Request";
            case Query_My_User_Info_Response: return "Query_My_User_Info_Response";
            case Request_File_Access_Request: return "Request_File_Access_Request";
            case Request_File_Access_Response: return "Request_File_Access_Response";
            case Send_Chat_Message_Request: return "Send_Chat_Message_Request";
            case Send_Chat_Message_Response: return "Send_Chat_Message_Response";
            case Get_Chat_Messages_Request: return "Get_Chat_Messages_Request";
            case Get_Chat_Messages_Response: return "Get_Chat_Messages_Response";
            case Query_Chat_Info_Request: return "Query_Chat_Info_Request";
            case Query_Chat_Info_Response: return "Query_Chat_Info_Response";
            case Get_Or_Create_Private_Chat_Request: return "Get_Or_Create_Private_Chat_Request";
            case Get_Or_Create_Private_Chat_Response: return "Get_Or_Create_Private_Chat_Response";
            case Get_My_Chats_Request: return "Get_My_Chats_Request";
            case Get_My_Chats_Response: return "Get_My_Chats_Response";
            case Get_My_Favourite_Chats_Request: return "Get_My_Favourite_Chats_Request";
            case Get_My_Favourite_Chats_Response: return "Get_My_Favourite_Chats_Response";
            case Search_My_Chats_Request: return "Search_My_Chats_Request";
            case Search_My_Chats_Response: return "Search_My_Chats_Response";
            case Get_Another_User_From_Private_Chat_Request: return "Get_Another_User_From_Private_Chat_Request";
            case Get_Another_User_From_Private_Chat_Response: return "Get_Another_User_From_Private_Chat_Response";
            case Set_Chat_Favourited_Request: return "Set_Chat_Favourited_Request";
            case Set_Chat_Favourited_Response: return "Set_Chat_Favourited_Response";
            case Get_User_Id_By_Username_Request: return "Get_User_Id_By_Username_Request";
            case Get_User_Id_By_Username_Response: return "Get_User_Id_By_Username_Response";
            case Create_Group_Request: return "Create_Group_Request";
            case Create_Group_Response: return "Create_Group_Response";
            case Set_Chat_Admin_Request: return "Set_Chat_Admin_Request";
            case Set_Chat_Admin_Response: return "Set_Chat_Admin_Response";
            case Resolve_Chat_Identifier_Request: return "Resolve_Chat_Identifier_Request";
            case Resolve_Chat_Identifier_Response: return "Resolve_Chat_Identifier_Response";
            case Join_Chat_Request: return "Join_Chat_Request";
            case Join_Chat_Response: return "Join_Chat_Response";
            case Remove_Chat_Member_Request: return "Remove_Chat_Member_Request";
            case Remove_Chat_Member_Response: return "Remove_Chat_Member_Response";
            case Update_Chat_Settings_Request: return "Update_Chat_Settings_Request";
            case Update_Chat_Settings_Response: return "Update_Chat_Settings_Response";
            case Get_Chat_Admins_Request: return "Get_Chat_Admins_Request";
            case Get_Chat_Admins_Response: return "Get_Chat_Admins_Response";
            case Get_Chat_Members_Request: return "Get_Chat_Members_Request";
            case Get_Chat_Members_Response: return "Get_Chat_Members_Response";
            case Add_Chat_Admin_Request: return "Add_Chat_Admin_Request";
            case Add_Chat_Admin_Response: return "Add_Chat_Admin_Response";
            case Edit_Chat_Admin_Permissions_Request: return "Edit_Chat_Admin_Permissions_Request";
            case Edit_Chat_Admin_Permissions_Response: return "Edit_Chat_Admin_Permissions_Response";
            case Remove_Chat_Admin_Request: return "Remove_Chat_Admin_Request";
            case Remove_Chat_Admin_Response: return "Remove_Chat_Admin_Response";
            case Verify_Password_Identity_Request: return "Verify_Password_Identity_Request";
            case Verify_Password_Identity_Response: return "Verify_Password_Identity_Response";
            case Change_Password_Request: return "Change_Password_Request";
            case Change_Password_Response: return "Change_Password_Response";
            case Edit_Chat_Message_Request: return "Edit_Chat_Message_Request";
            case Edit_Chat_Message_Response: return "Edit_Chat_Message_Response";
            case Start_Meeting_Request: return "Start_Meeting_Request";
            case Start_Meeting_Response: return "Start_Meeting_Response";
            case Get_Meeting_Token_Request: return "Get_Meeting_Token_Request";
            case Get_Meeting_Token_Response: return "Get_Meeting_Token_Response";
            case End_Meeting_Request: return "End_Meeting_Request";
            case End_Meeting_Response: return "End_Meeting_Response";
            case Get_Active_Meeting_Request: return "Get_Active_Meeting_Request";
            case Get_Active_Meeting_Response: return "Get_Active_Meeting_Response";
            case Exchange_OAuth_Code_Request: return "Exchange_OAuth_Code_Request";
            case Exchange_OAuth_Code_Response: return "Exchange_OAuth_Code_Response";
            case Get_OAuth_Bindings_Request: return "Get_OAuth_Bindings_Request";
            case Get_OAuth_Bindings_Response: return "Get_OAuth_Bindings_Response";
            case Unbind_OAuth_Request: return "Unbind_OAuth_Request";
            case Unbind_OAuth_Response: return "Unbind_OAuth_Response";
            case Receive_Chat_Message_Event: return "Receive_Chat_Message_Event";
            case Update_My_Chats_Event: return "Update_My_Chats_Event";
            case Message_Edited_Event: return "Message_Edited_Event";
            case Meeting_Started_Event: return "Meeting_Started_Event";
            case Meeting_Ended_Event: return "Meeting_Ended_Event";
            default: return "Unknown(" + id + ")";
        }
    }
}